use std::sync::LazyLock;

use crate::types::CatalogEntry;

/// Relic rewards catalog — common items from Warframe relic drops.
/// Production data comes from WFCD Relics.json; here we embed the most common items.
pub static CATALOG: LazyLock<Vec<CatalogEntry>> = LazyLock::new(|| {
    vec![
        // ─── Common drops (appear in many relics) ──────────────────────────────
        entry("Forma Blueprint", "Bronze"),
        entry("Forma Blueprint", "Bronze"), // duplicate kept for weight

        // ─── Lith relic rewards ────────────────────────────────────────────────
        entry("Frost Prime Blueprint", "Gold"),
        entry("Frost Prime Neuroptics Blueprint", "Silver"),
        entry("Frost Prime Chassis Blueprint", "Bronze"),
        entry("Frost Prime Systems Blueprint", "Bronze"),
        entry("Mag Prime Blueprint", "Gold"),
        entry("Mag Prime Neuroptics Blueprint", "Silver"),
        entry("Mag Prime Chassis Blueprint", "Bronze"),
        entry("Mag Prime Systems Blueprint", "Bronze"),
        entry("Ember Prime Blueprint", "Gold"),
        entry("Ember Prime Neuroptics Blueprint", "Silver"),
        entry("Ember Prime Chassis Blueprint", "Bronze"),
        entry("Ember Prime Systems Blueprint", "Bronze"),
        entry("Lato Prime Blueprint", "Silver"),
        entry("Lato Prime Receiver", "Bronze"),
        entry("Skana Prime Blueprint", "Silver"),
        entry("Skana Prime Blade", "Bronze"),

        // ─── Meso relic rewards ────────────────────────────────────────────────
        entry("Saryn Prime Blueprint", "Gold"),
        entry("Saryn Prime Neuroptics Blueprint", "Silver"),
        entry("Saryn Prime Chassis Blueprint", "Bronze"),
        entry("Saryn Prime Systems Blueprint", "Bronze"),
        entry("Valkyr Prime Blueprint", "Gold"),
        entry("Valkyr Prime Neuroptics Blueprint", "Silver"),
        entry("Valkyr Prime Chassis Blueprint", "Bronze"),
        entry("Valkyr Prime Systems Blueprint", "Bronze"),
        entry("Banshee Prime Blueprint", "Gold"),
        entry("Banshee Prime Neuroptics Blueprint", "Silver"),
        entry("Banshee Prime Chassis Blueprint", "Bronze"),
        entry("Banshee Prime Systems Blueprint", "Bronze"),
        entry("Reaper Prime Blueprint", "Silver"),
        entry("Reaper Prime Blade", "Bronze"),
        entry("Boar Prime Blueprint", "Silver"),
        entry("Boar Prime Receiver", "Bronze"),

        // ─── Neo relic rewards ─────────────────────────────────────────────────
        entry("Nova Prime Blueprint", "Gold"),
        entry("Nova Prime Neuroptics Blueprint", "Silver"),
        entry("Nova Prime Chassis Blueprint", "Bronze"),
        entry("Nova Prime Systems Blueprint", "Bronze"),
        entry("Loki Prime Blueprint", "Gold"),
        entry("Loki Prime Neuroptics Blueprint", "Silver"),
        entry("Loki Prime Chassis Blueprint", "Bronze"),
        entry("Loki Prime Systems Blueprint", "Bronze"),
        entry("Trinity Prime Blueprint", "Gold"),
        entry("Trinity Prime Neuroptics Blueprint", "Silver"),
        entry("Trinity Prime Chassis Blueprint", "Bronze"),
        entry("Trinity Prime Systems Blueprint", "Bronze"),
        entry("Fang Prime Blueprint", "Silver"),
        entry("Fang Prime Blade", "Bronze"),
        entry("Fang Prime Handle", "Bronze"),
        entry("Frost Prime Blueprint", "Gold"),

        // ─── Axi relic rewards ─────────────────────────────────────────────────
        entry("Mirage Prime Blueprint", "Gold"),
        entry("Mirage Prime Neuroptics Blueprint", "Silver"),
        entry("Mirage Prime Chassis Blueprint", "Bronze"),
        entry("Mirage Prime Systems Blueprint", "Bronze"),
        entry("Chroma Prime Blueprint", "Gold"),
        entry("Chroma Prime Neuroptics Blueprint", "Silver"),
        entry("Chroma Prime Chassis Blueprint", "Bronze"),
        entry("Chroma Prime Systems Blueprint", "Bronze"),
        entry("Volt Prime Blueprint", "Gold"),
        entry("Volt Prime Neuroptics Blueprint", "Silver"),
        entry("Volt Prime Chassis Blueprint", "Bronze"),
        entry("Volt Prime Systems Blueprint", "Bronze"),
        entry("Vauban Prime Blueprint", "Gold"),
        entry("Vauban Prime Neuroptics Blueprint", "Silver"),
        entry("Vauban Prime Chassis Blueprint", "Bronze"),
        entry("Vauban Prime Systems Blueprint", "Bronze"),
        entry("Ash Prime Blueprint", "Gold"),
        entry("Ash Prime Neuroptics Blueprint", "Silver"),
        entry("Ash Prime Chassis Blueprint", "Bronze"),
        entry("Ash Prime Systems Blueprint", "Bronze"),
        entry("Nikana Prime Blueprint", "Gold"),
        entry("Nikana Prime Blade", "Silver"),
        entry("Nikana Prime Hilt", "Bronze"),
        entry("Galatine Prime Blueprint", "Gold"),
        entry("Galatine Prime Blade", "Silver"),
        entry("Galatine Prime Handle", "Bronze"),

        // ─── Weapon parts (common in relics) ───────────────────────────────────
        entry("Braton Prime Blueprint", "Silver"),
        entry("Braton Prime Barrel", "Bronze"),
        entry("Braton Prime Receiver", "Bronze"),
        entry("Braton Prime Stock", "Bronze"),
        entry("Sybaris Prime Blueprint", "Silver"),
        entry("Sybaris Prime Barrel", "Bronze"),
        entry("Sybaris Prime Receiver", "Bronze"),
        entry("Tigris Prime Blueprint", "Silver"),
        entry("Tigris Prime Barrel", "Bronze"),
        entry("Tigris Prime Receiver", "Bronze"),
        entry("Tigris Prime Stock", "Bronze"),
        entry("Soma Prime Blueprint", "Silver"),
        entry("Soma Prime Barrel", "Bronze"),
        entry("Soma Prime Receiver", "Bronze"),
        entry("Soma Prime Stock", "Bronze"),
        entry("Akstiletto Prime Blueprint", "Silver"),
        entry("Akstiletto Prime Barrel", "Bronze"),
        entry("Akstiletto Prime Receiver", "Bronze"),
        entry("Spira Prime Blueprint", "Silver"),
        entry("Spira Prime Blade", "Bronze"),
        entry("Spira Prime Handle", "Bronze"),
        entry("Scarlet Kyatt Blueprint", "Silver"),
        entry("Velox Blueprint", "Silver"),

        // ─── Alternox Prime ─────────────────────────────────────────────────────
        entry("Alternox Prime Blueprint", "Gold"),
        entry("Alternox Prime Barrel", "Silver"),
        entry("Alternox Prime Receiver", "Bronze"),
        entry("Alternox Prime Stock", "Bronze"),

        // ─── Archwing / Operator ───────────────────────────────────────────────
        entry("Elytron Blueprint", "Gold"),
        entry("Itzal Blueprint", "Gold"),
        entry("Amesha Blueprint", "Gold"),
        entry("Odonata Blueprint", "Gold"),

        // ─── Sentinel ──────────────────────────────────────────────────────────
        entry("Carrier Prime Blueprint", "Gold"),
        entry("Carrier Prime Cerebrum", "Silver"),
        entry("Carrier Prime Carapace", "Bronze"),
        entry("Carrier Prime Systems", "Bronze"),
        entry("Djinn Blueprint", "Gold"),

        // ─── Warframe parts (popular) ──────────────────────────────────────────
        entry("Nezha Prime Blueprint", "Gold"),
        entry("Nezha Prime Neuroptics Blueprint", "Silver"),
        entry("Nezha Prime Chassis Blueprint", "Bronze"),
        entry("Nezha Prime Systems Blueprint", "Bronze"),
        entry("Wukong Prime Blueprint", "Gold"),
        entry("Wukong Prime Neuroptics Blueprint", "Silver"),
        entry("Wukong Prime Chassis Blueprint", "Bronze"),
        entry("Wukong Prime Systems Blueprint", "Bronze"),
        entry("Atlas Prime Blueprint", "Gold"),
        entry("Atlas Prime Neuroptics Blueprint", "Silver"),
        entry("Atlas Prime Chassis Blueprint", "Bronze"),
        entry("Atlas Prime Systems Blueprint", "Bronze"),
        entry("Khora Prime Blueprint", "Gold"),
        entry("Khora Prime Neuroptics Blueprint", "Silver"),
        entry("Khora Prime Chassis Blueprint", "Bronze"),
        entry("Khora Prime Systems Blueprint", "Bronze"),
        entry("Garuda Prime Blueprint", "Gold"),
        entry("Garuda Prime Neuroptics Blueprint", "Silver"),
        entry("Garuda Prime Chassis Blueprint", "Bronze"),
        entry("Garuda Prime Systems Blueprint", "Bronze"),
        entry("Baruuk Prime Blueprint", "Gold"),
        entry("Baruuk Prime Neuroptics Blueprint", "Silver"),
        entry("Baruuk Prime Chassis Blueprint", "Bronze"),
        entry("Baruuk Prime Systems Blueprint", "Bronze"),
        entry("Hildryn Prime Blueprint", "Gold"),
        entry("Hildryn Prime Neuroptics Blueprint", "Silver"),
        entry("Hildryn Prime Chassis Blueprint", "Bronze"),
        entry("Hildryn Prime Systems Blueprint", "Bronze"),
        entry("Grendel Prime Blueprint", "Gold"),
        entry("Grendel Prime Neuroptics Blueprint", "Silver"),
        entry("Grendel Prime Chassis Blueprint", "Bronze"),
        entry("Grendel Prime Systems Blueprint", "Bronze"),
        entry("Gauss Prime Blueprint", "Gold"),
        entry("Gauss Prime Neuroptics Blueprint", "Silver"),
        entry("Gauss Prime Chassis Blueprint", "Bronze"),
        entry("Gauss Prime Systems Blueprint", "Bronze"),
        entry("Ember Prime Blueprint", "Gold"),
        entry("Sevagoth Prime Blueprint", "Gold"),
        entry("Sevagoth Prime Neuroptics Blueprint", "Silver"),
        entry("Sevagoth Prime Chassis Blueprint", "Bronze"),
        entry("Sevagoth Prime Systems Blueprint", "Bronze"),
        entry("Yareli Prime Blueprint", "Gold"),
        entry("Yareli Prime Neuroptics Blueprint", "Silver"),
        entry("Yareli Prime Chassis Blueprint", "Bronze"),
        entry("Yareli Prime Systems Blueprint", "Bronze"),
        entry("Caliban Prime Blueprint", "Gold"),
        entry("Caliban Prime Neuroptics Blueprint", "Silver"),
        entry("Caliban Prime Chassis Blueprint", "Bronze"),
        entry("Caliban Prime Systems Blueprint", "Bronze"),
        entry("Lavos Prime Blueprint", "Gold"),
        entry("Lavos Prime Neuroptics Blueprint", "Silver"),
        entry("Lavos Prime Chassis Blueprint", "Bronze"),
        entry("Lavos Prime Systems Blueprint", "Bronze"),
        entry("Voruna Prime Blueprint", "Gold"),
        entry("Voruna Prime Neuroptics Blueprint", "Silver"),
        entry("Voruna Prime Chassis Blueprint", "Bronze"),
        entry("Voruna Prime Systems Blueprint", "Bronze"),
        entry("Citrine Prime Blueprint", "Gold"),
        entry("Citrine Prime Neuroptics Blueprint", "Silver"),
        entry("Citrine Prime Chassis Blueprint", "Bronze"),
        entry("Citrine Prime Systems Blueprint", "Bronze"),
        entry("Kullervo Prime Blueprint", "Gold"),
        entry("Kullervo Prime Neuroptics Blueprint", "Silver"),
        entry("Kullervo Prime Chassis Blueprint", "Bronze"),
        entry("Kullervo Prime Systems Blueprint", "Bronze"),
        entry("Styanax Prime Blueprint", "Gold"),
        entry("Styanax Prime Neuroptics Blueprint", "Silver"),
        entry("Styanax Prime Chassis Blueprint", "Bronze"),
        entry("Styanax Prime Systems Blueprint", "Bronze"),
        entry("Voruna Prime Blueprint", "Gold"),
        entry("Qorvex Prime Blueprint", "Gold"),
        entry("Qorvex Prime Neuroptics Blueprint", "Silver"),
        entry("Qorvex Prime Chassis Blueprint", "Bronze"),
        entry("Qorvex Prime Systems Blueprint", "Bronze"),
        entry("Dante Prime Blueprint", "Gold"),
        entry("Dante Prime Neuroptics Blueprint", "Silver"),
        entry("Dante Prime Chassis Blueprint", "Bronze"),
        entry("Dante Prime Systems Blueprint", "Bronze"),
    ]
});

fn entry(name: &str, rarity: &str) -> CatalogEntry {
    CatalogEntry {
        unique_name: name.to_string(),
        name: name.to_string(),
        rarity: rarity.to_string(),
    }
}

/// Get the catalog as (unique_name, name) pairs for matching.
pub fn catalog_pairs() -> Vec<(String, String)> {
    CATALOG.iter().map(|e| (e.unique_name.clone(), e.name.clone())).collect()
}
